#!/bin/sh

echo "\033[34m \033[1mStarting installation...\033[32m"


count=0
total=15
pstr="[=======================================================================]"

while [ $count -lt $total ]; do
	sleep 0.2 # this is fake ! OMG MOM GET THE KAMERA
	count=$(( $count + 1 ))
	pd=$(( $count * 73 / $total ))
	printf "\r%3d.%1d%% %.${pd}s" $(( $count * 100 / $total )) $(( ($count * 1000 / $total) % 10 )) $pstr
done

echo "\033[0m"

#git clone https://github.com/seluj78/myconfigfiles.git /tmp/setupconfig

echo "\033[34m \033[1mNow installing the gpush command\033[0m"

#touch ~/.gpush.sh
#chmod 777 ~/.gpush.sh
#cat /tmp/setupconfig/sources/gpush > ~/.gpush.sh

echo "\033[34m \033[1m\033[0m"

echo "Now configuring your vimrc and zshrc"
#cat /tmp/setupconfig/sources/vimrc >> ~/.vimrc
#cat /tmp/setupconfig/sources/zshrc >> ~/.zshrc

echo "\033[34m \033[1m\033[0m"

echo "Creating backupdir for vim so you don't get the .swp files"
#mkdir ~/.vim

echo "\033[34m \033[1m\033[0m"

echo "Done installing, removing temp files"
#rm -rf /tmp/setupconfig
