plugins=(
  git
  zsh-autosuggestions
  chucknorris
  zsh-256color
  alias-tips
  apache2
  autoupdate
  careful_rm
  colored-man-pages
  quoter-zsh
  randeme
  send
  startup-time
  oh-my-matrix
  notify
)

alias gpush="~/.gpush.sh"
alias gww="gcc -Werror -Wall -Wextra"
alias gcom="git commit -a -m"
alias gadd="git add -A"

export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan

alias norm="norminette -R CheckForbiddenSourceHeader"
alias norme="norm"

alias mak="make"
alias mke="make"
alias makw="make"
alias mkw="make"
alias male="make"


export PATH=$PATH:/Users/jlasne/bin/bats/bin
export PATH="/Users/jlasne/.brew/bin:$PATH"

eval $(thefuck --alias)
ansiweather
chuck_cow

# zsh-bd
. $HOME/.zsh/plugins/bd/bd.zsh
source $HOME/.oh-my-zsh/plugins/calc/calc.plugin.zsh
echo "Remember: randeme_rm if you don't like this theme !"
